### ISSUE TITLE
Wrong number of samples in docstring

### ISSUE THREAD

**Issue by jdossgollin** [lrennels/GlobalSensitivityAnalysis.jl#43]
The docs for `sample(data::SobolData)` say the following

https://github.com/lrennels/GlobalSensitivityAnalysis.jl/blob/197043741a4180c434d59b84870a180535af1b2d/src/sample_sobol.jl#L28

However the code produces `N * (2D + 2)` samples

**Comment by lrennels** [comment]
@jdossgollin thank you for pointing this out, it will produce `N * (D + 2)` only if you do not calculate second order indices, and as you say if you do calculate second order indices it will produce `N * (2D + 2)`.  I will fix this now!

**Comment by lrennels** [comment]
Fixed in #44
